Trap exits to cleanup and add debug option

diff --git a/scripts/bootstrap_pi b/scripts/bootstrap_pi
--- a/scripts/bootstrap_pi
+++ b/scripts/bootstrap_pi
@@ -2,25 +2,49 @@
 # Install AmpliPi from scratch on a new pi compute module
 # This script is mainly intended for MicroNova employees to bringup Pi's. Your AmpliPi device should already have this configuration.
 
-# stop on errors
-set -e
+helptext="Usage: bootstrap_pi diskpath [hostname] [--debug] [-h|--help]
+Bootstrap a Raspberry Pi Compute Module for first-time AmpliPi setup.
 
-# arguments
-hostname=${2:-amplipi}
-diskpath=${1:-/dev/sda}
+  diskpath:   The path to the mounted raspberry pi disk. Should be /dev/sdX
+  hostname:   The hostname to set on the pi, so once this script successfully completes
+              connect via {hostname}.local. Default is amplipi
+  --debug:    Will print all commands to be run and disable cleanup on exit
+  -h, --help: Print this help text.
+"
 
-only_list_disks=false
-if [[ $# < 1 ]]; then
-  printf "Usage: bootstrap_pi diskpath [hostname]\n"
-  printf "  diskpath should be /dev/sdX.\n"
-  printf "  hostname will be set on the pi, so once this script successfully completes\n"
-  printf "    connect via {hostname}.local. Default is amplipi\n"
+hostname='amplipi'
+diskpath_set=false
+host_set=false
+debug=false
+while [[ "$#" -gt 0 ]]; do
+  case $1 in
+    --debug) debug=true ;;
+    -h|--help) printf "$helptext"; exit 0 ;;
+    *) if ! $diskpath_set; then
+        diskpath=$1
+        diskpath_set=true
+      elif ! $host_set; then
+        hostname=$1
+        host_set=true
+      else
+        echo "Unknown parameter passed: $1";
+        printf "$helptext";
+        exit 1
+      fi
+      ;;
+  esac
+  shift
+done
+
+$debug && set -x
+
+if ! $diskpath_set; then
+  printf "$helptext"
   printf "\ndiskpath is required!\n"
   printf "This script will exit after connecting to the pi and listing disks.\n"
   printf "Re-run this script with the correct diskpath to bootstrap.\n"
   read -p "Press any key to continue" -n 1
   printf "\n"
-  only_list_disks=true
 fi
 
 current_dir="$(dirname "$(realpath ${BASH_SOURCE[0]})")"
@@ -30,13 +54,26 @@ amplipi_config_dir="$(realpath $current_dir/../config)"
 tmpdir=$(mktemp --directory)
 pushd $tmpdir
 
+# cleanup temp files on exit
 cleanup () {
-  sudo umount /mnt/pi-boot 2>/dev/null || true # don't error if not mounted
-  sudo umount /mnt/pi-root 2>/dev/null || true
-  if [[ -d $tmpdir ]] ; then
-    rm -rf $tmpdir
+  if ! $debug; then
+    sudo umount /mnt/pi-boot 2>/dev/null
+    sudo umount /mnt/pi-root 2>/dev/null
+    if [[ -d $tmpdir ]] ; then
+      rm -rf $tmpdir
+    fi
+  else
+    printf "\nExited while in debug mode.\n"
+    printf "Not unmounting: \n"
+    printf "  %s\n" /mnt/pi-boot /mnt/pi-root
+    printf "Not removing:\n"
+    printf "  %s\n" $tmpdir
   fi
+  exit 0
 }
+
+# trap any errors and CTRL-C
+trap cleanup INT TERM ERR
 
 echo "Downloading Raspberry Pi boot"
 git clone --depth=1 https://github.com/raspberrypi/usbboot
@@ -65,15 +102,18 @@ read -p "Press any key and then plug in the AmpliPi" -n 1
 sudo ./rpiboot
 popd # usbboot
 
-if $only_list_disks; then
-  sleep 2 # TODO: how to determine the disk has been attached?
+print_disks () {
   printf "\nListing available disks sorted by time.\n"
   printf "The pi should be the first /dev/sdX.\n\n"
   for d in $(ls -t -1 /dev/sd?); do
     lsblk -plndo name,size $d
   done
+}
+
+if ! $diskpath_set; then
+  sleep 2 # TODO: how to determine the disk has been attached?
+  print_disks
   cleanup
-  exit 0
 fi
 
 release=2020-08-20-raspios-buster-armhf-lite
@@ -93,9 +133,11 @@ if [[ -e $diskpath ]]; then
   echo "Valid $diskpath device found"
 elif [[ ! -e $diskpath ]]; then
   echo "ERROR: Expected device $diskpath not found"
+  print_disks
   exit 1
 else
   echo "ERROR: Can't handle the devices/partitions detected, maybe dd failed or other devices were detected"
+  print_disks
   exit 1
 fi
 
@@ -125,7 +167,6 @@ sudo cp $amplipi_config_dir/boot_config.txt /mnt/pi-boot/config.txt
 # cleanup
 popd # /mnt/pi-root
 popd # /tmp/*
-cleanup
 
 echo "Bootstrapping successful. Please complete the following steps:
   1. Disconnect the service USB cable.
@@ -133,3 +174,4 @@ echo "Bootstrapping successful. Please complete the following steps:
   3. Plug it back in to power it on.
   4. Run the deploy script to install the latest AmpliPi version.
 "
+cleanup
