Retry on mount failure and change hostname param to need --hostname

diff --git a/scripts/bootstrap_pi b/scripts/bootstrap_pi
--- a/scripts/bootstrap_pi
+++ b/scripts/bootstrap_pi
@@ -2,10 +2,10 @@
 # Install AmpliPi from scratch on a new pi compute module
 # This script is mainly intended for MicroNova employees to bringup Pi's. Your AmpliPi device should already have this configuration.
 
-helptext="Usage: bootstrap_pi diskpath [hostname] [--debug] [-h|--help]
+helptext="Usage: bootstrap_pi diskpath [--hostname NAME] [--cli-only] [--debug] [-h|--help]
 Bootstrap a Raspberry Pi Compute Module for first-time AmpliPi setup.
 
-  hostname:   The hostname to set on the pi, so once this script successfully
+  --hostname: The hostname to set on the pi, so once this script successfully
               completes connect via {hostname}.local. Default is amplipi
   --cli-only: Use the lite version of Raspberry Pi OS which does not have a
               desktop environment
@@ -14,22 +14,25 @@ Bootstrap a Raspberry Pi Compute Module for first-time AmpliPi setup.
 "
 
 hostname='amplipi'
-host_set=false
 debug=false
 lite=false
 while [[ "$#" -gt 0 ]]; do
   case $1 in
-    --debug) debug=true ;;
+    --hostname)
+        if (($# > 1)); then
+          hostname=$2; shift
+        else
+          printf "--hostname requires a second parameter\n\n"
+          printf "$helptext"
+          exit 1
+        fi
+      ;;
     --cli-only) lite=true ;;
+    --debug) debug=true ;;
     -h|--help) printf "$helptext"; exit 0 ;;
-    *) if ! $host_set; then
-        hostname=$1
-        host_set=true
-      else
-        echo "Unknown parameter passed: $1";
-        printf "$helptext";
+    *)  printf "Unknown parameter passed: $1\n\n"
+        printf "$helptext"
         exit 1
-      fi
       ;;
   esac
   shift
@@ -154,63 +157,85 @@ echo "Go get a coffee or something :)"
 sudo dd if=$release.img of=$diskpath bs=4MiB status=progress
 popd # $release
 
-echo "Editing some configuration"
-sudo mkdir -p /mnt/pi-boot
-sudo mkdir -p /mnt/pi-root
-echo "Made /mnt/pi-[br]oot, waiting a bit..."
-sleep 5
-echo "Mounting $diskpath-part1 at /mnt/pi-boot"
-#sudo mount ${diskpath}1 /mnt/pi-boot # boot partition
-#sudo mount ${diskpath}2 /mnt/pi-root # root filesystem partition
-sudo mount $diskpath-part1 /mnt/pi-boot # boot partition
-echo "Mounting $diskpath-part2 at /mnt/pi-boot"
-sudo mount $diskpath-part2 /mnt/pi-root # root filesystem partition
+# First arg is partition path to mount
+config_boot () {
+  sudo mkdir -p /mnt/pi-boot
+  sudo mount $1 /mnt/pi-boot # boot partition
+  pushd /mnt/pi-boot
 
-ls /mnt/pi-boot
-ls /mnt/pi-root
+  echo "Enabling SSH access"
+  sudo touch ssh
 
-pushd /mnt/pi-boot
+  # extra config to make sure the USB serial tty is disabled
+  # (we use this to communicate with the AmpliPi preamp)
+  echo "Disabling USB serial tty"
+  CMDLINE=cmdline.txt
+  sudo sed -i $CMDLINE -e "s/console=ttyAMA0,[0-9]\+ //"
+  sudo sed -i $CMDLINE -e "s/console=serial0,[0-9]\+ //"
 
-echo "Enabling SSH access"
-sudo touch ssh
+  popd # /mnt/pi-boot
+}
 
-# extra config to make sure the USB serial tty is disabled (we use this to communicate with the AmpliPi preamp)
-echo "Disabling USB serial tty"
-CMDLINE=cmdline.txt
-sudo sed -i $CMDLINE -e "s/console=ttyAMA0,[0-9]\+ //"
-sudo sed -i $CMDLINE -e "s/console=serial0,[0-9]\+ //"
+# First arg is partition path to mount
+config_root () {
+  sudo mkdir -p /mnt/pi-root
+  sudo mount $1 /mnt/pi-root # root filesystem partition
+  pushd /mnt/pi-root
 
-popd # /mnt/pi-boot
+  printf "Setting the hostname to "
+  echo $hostname | sudo tee etc/hostname
+  # need to change hostname reference too
+  # (if you don't it causes a message to be reported after every sudo)
+  sudo sed -i'' -e "s/raspberrypi/$hostname/" etc/hosts
 
-pushd /mnt/pi-root
+  # add pi user manually to dialout group, avoiding an additional restart
+  echo "Adding the pi user to the dialout group"
+  sudo sed -i'' -r -e 's/dialout:x:([0-9]+:.*)/dialout:x:\1,pi/' -e 's/:,pi/:pi/' -e 's/pi,pi/pi/' etc/group
 
-echo "Setting the hostname to $hostname"
-echo $hostname | sudo tee etc/hostname
-sudo sed -i'' -e "s/raspberrypi/$hostname/" etc/hosts # need to change hostname reference too (if you don't it causes a message to be reported after every sudo)
+  echo "Copying the pi's boot configuration"
+  sudo cp $amplipi_config_dir/boot_config.txt /mnt/pi-boot/config.txt
 
-# add pi user manually to dialout group, avoiding an additional restart
-echo "Adding the pi user to the dialout group"
-sudo sed -i'' -r -e 's/dialout:x:([0-9]+:.*)/dialout:x:\1,pi/' -e 's/:,pi/:pi/' -e 's/pi,pi/pi/' etc/group
+  # extra config to enable i2c (from do-i2c in raspi-config bash script)
+  BLACKLIST=etc/modprobe.d/raspi-blacklist.conf
+  if ! [ -e $BLACKLIST ]; then
+    sudo touch $BLACKLIST
+  fi
+  sudo sed $BLACKLIST -i -e "s/^\(blacklist[[:space:]]*i2c[-_]bcm2708\)/#\1/"
+  sudo sed etc/modules -i -e "s/^#[[:space:]]*\(i2c[-_]dev\)/\1/"
+  if ! grep -q "^i2c[-_]dev" etc/modules; then
+    printf "i2c-dev\n" | sudo tee -a etc/modules
+  fi
 
-echo "Copying the pi's boot configuration"
-sudo cp $amplipi_config_dir/boot_config.txt /mnt/pi-boot/config.txt
+  popd # /mnt/pi-root
+}
 
-# extra config to enable i2c (from do-i2c in raspi-config bash script)
-BLACKLIST=etc/modprobe.d/raspi-blacklist.conf
-if ! [ -e $BLACKLIST ]; then
-  sudo touch $BLACKLIST
+# it can take a second or two for the new partitions to show up
+printf "\nChecking for the new root and boot partitions\n"
+boot_part=false
+root_part=false
+for i in {1..10}; do
+  sleep 0.5
+  if ! $boot_part && [ -e $diskpath-part1 ]; then
+    boot_part=true
+    echo "Editing boot configuration"
+    config_boot $diskpath-part1
+  fi
+  if ! $root_part && [ -e $diskpath-part2 ]; then
+    root_part=true
+    echo "Editing root configuration"
+    config_root $diskpath-part2
+  fi
+  $boot_part && $root_part && break
+done
+if ! $boot_part || ! $root_part ; then
+  echo "Error: Failed to find boot and root partitions"
+  cleanup
 fi
-sudo sed $BLACKLIST -i -e "s/^\(blacklist[[:space:]]*i2c[-_]bcm2708\)/#\1/"
-sudo sed etc/modules -i -e "s/^#[[:space:]]*\(i2c[-_]dev\)/\1/"
-if ! grep -q "^i2c[-_]dev" etc/modules; then
-  printf "i2c-dev\n" | sudo tee -a etc/modules
-fi
 
-# cleanup
-popd # /mnt/pi-root
 popd # /tmp/*
 
-echo "Bootstrapping successful. Please complete the following steps:
+echo "
+Bootstrapping successful. Please complete the following steps:
   1. Disconnect the service USB cable.
   2. Unplug the AmpliPi unit.
   3. Plug it back in to power it on.
