Find RPi disk path by id

diff --git a/scripts/bootstrap_pi b/scripts/bootstrap_pi
--- a/scripts/bootstrap_pi
+++ b/scripts/bootstrap_pi
@@ -5,7 +5,6 @@
 helptext="Usage: bootstrap_pi diskpath [hostname] [--debug] [-h|--help]
 Bootstrap a Raspberry Pi Compute Module for first-time AmpliPi setup.
 
-  diskpath:   The path to the mounted raspberry pi disk. Should be /dev/sdX
   hostname:   The hostname to set on the pi, so once this script successfully
               completes connect via {hostname}.local. Default is amplipi
   --cli-only: Use the lite version of Raspberry Pi OS which does not have a
@@ -15,7 +14,6 @@ Bootstrap a Raspberry Pi Compute Module for first-time AmpliPi setup.
 "
 
 hostname='amplipi'
-diskpath_set=false
 host_set=false
 debug=false
 lite=false
@@ -24,10 +22,7 @@ while [[ "$#" -gt 0 ]]; do
     --debug) debug=true ;;
     --cli-only) lite=true ;;
     -h|--help) printf "$helptext"; exit 0 ;;
-    *) if ! $diskpath_set; then
-        diskpath=$1
-        diskpath_set=true
-      elif ! $host_set; then
+    *) if ! $host_set; then
         hostname=$1
         host_set=true
       else
@@ -41,15 +36,6 @@ while [[ "$#" -gt 0 ]]; do
 done
 
 $debug && set -x
-
-if ! $diskpath_set; then
-  printf "$helptext"
-  printf "\ndiskpath is required!\n"
-  printf "This script will exit after connecting to the pi and listing disks.\n"
-  printf "Re-run this script with the correct diskpath to bootstrap.\n"
-  read -p "Press any key to continue" -n 1
-  printf "\n"
-fi
 
 current_dir="$(dirname "$(realpath ${BASH_SOURCE[0]})")"
 amplipi_config_dir="$(realpath $current_dir/../config)"
@@ -111,6 +97,7 @@ fi
 
 make
 
+# instruct user on manual boot process
 echo -e "\nPlug in a usb cable from the service port to your computer. Keep AmpliPi Unplugged / Powered OFF for now."
 read -p "Press any key to continue" -n 1
 echo  # newline
@@ -118,19 +105,20 @@ read -p "Press any key and then plug in the AmpliPi" -n 1
 sudo ./rpiboot
 popd # usbboot
 
-print_disks () {
-  printf "\nListing available disks sorted by time.\n"
-  printf "The pi should be the first /dev/sdX.\n\n"
-  for d in $(ls -t -1 /dev/sd?); do
-    lsblk -plndo name,size $d
-  done
-}
-
-
-sleep 2 # TODO: how to determine the disk has been attached?
-if ! [[ -e $diskpath ]]; then
-  printf "\n$diskpath is not available\n"
-  print_disks
+# wait for the Raspberry Pi to connect
+# it will show up as 0a5c:2764 without usbboot
+# it will show up as 0a5c:0001 when mounting as /dev/sdX
+connected=false
+for i in {1..10}; do
+  sleep 0.5
+  if lsusb -d 0a5c:0001 >/dev/null; then
+    printf "Connected to Raspberry Pi!\n\n"
+    connected=true
+    break
+  fi
+done
+if ! $connected; then
+  echo "Error: Failed to connect to Raspberry Pi"
   cleanup
 fi
 
@@ -151,34 +139,43 @@ pushd $release
 echo "Extracting Raspberry Pi OS"
 unzip $zip_file
 
-if [[ -e $diskpath ]]; then
-  echo "Valid $diskpath device found"
-elif [[ ! -e $diskpath ]]; then
-  echo "ERROR: Expected device $diskpath not found"
-  print_disks
-  exit 1
+# Check for Raspberry Pi device path
+disk_base_path=/dev/disk/by-id/usb-RPi-MSD
+diskpath=$(ls $disk_base_path* 2>/dev/null | head -n1)
+if [ ! -z $diskpath ]; then
+  echo "Raspberry Pi device found at $diskpath"
 else
-  echo "ERROR: Can't handle the devices/partitions detected, maybe dd failed or other devices were detected"
-  print_disks
-  exit 1
+  echo "ERROR: No Raspberry Pi device found at $disk_base_path*"
 fi
 
-echo "Copying the image to the AmpliPi. This takes about 5 minutes. Go get a coffee or something :)"
-sudo dd if=$release.img of=$diskpath bs=4MiB
+$lite && est_time=5 || est_time=10
+echo "Copying the image to the AmpliPi. This takes about $est_time minutes."
+echo "Go get a coffee or something :)"
+sudo dd if=$release.img of=$diskpath bs=4MiB status=progress
 popd # $release
 
 echo "Editing some configuration"
 sudo mkdir -p /mnt/pi-boot
 sudo mkdir -p /mnt/pi-root
-sudo mount ${diskpath}1 /mnt/pi-boot # boot partition
-sudo mount ${diskpath}2 /mnt/pi-root # root filesystem partition
+echo "Made /mnt/pi-[br]oot, waiting a bit..."
+sleep 5
+echo "Mounting $diskpath-part1 at /mnt/pi-boot"
+#sudo mount ${diskpath}1 /mnt/pi-boot # boot partition
+#sudo mount ${diskpath}2 /mnt/pi-root # root filesystem partition
+sudo mount $diskpath-part1 /mnt/pi-boot # boot partition
+echo "Mounting $diskpath-part2 at /mnt/pi-boot"
+sudo mount $diskpath-part2 /mnt/pi-root # root filesystem partition
+
+ls /mnt/pi-boot
+ls /mnt/pi-root
 
 pushd /mnt/pi-boot
 
-# enable SSH access
+echo "Enabling SSH access"
 sudo touch ssh
 
 # extra config to make sure the USB serial tty is disabled (we use this to communicate with the AmpliPi preamp)
+echo "Disabling USB serial tty"
 CMDLINE=cmdline.txt
 sudo sed -i $CMDLINE -e "s/console=ttyAMA0,[0-9]\+ //"
 sudo sed -i $CMDLINE -e "s/console=serial0,[0-9]\+ //"
@@ -187,14 +184,15 @@ popd # /mnt/pi-boot
 
 pushd /mnt/pi-root
 
-# set the hostname to amplipi
+echo "Setting the hostname to $hostname"
 echo $hostname | sudo tee etc/hostname
 sudo sed -i'' -e "s/raspberrypi/$hostname/" etc/hosts # need to change hostname reference too (if you don't it causes a message to be reported after every sudo)
 
 # add pi user manually to dialout group, avoiding an additional restart
+echo "Adding the pi user to the dialout group"
 sudo sed -i'' -r -e 's/dialout:x:([0-9]+:.*)/dialout:x:\1,pi/' -e 's/:,pi/:pi/' -e 's/pi,pi/pi/' etc/group
 
-# copy the pi's boot configuration
+echo "Copying the pi's boot configuration"
 sudo cp $amplipi_config_dir/boot_config.txt /mnt/pi-boot/config.txt
 
 # extra config to enable i2c (from do-i2c in raspi-config bash script)
