Add uv install and configuration step to ensure we use the right python

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -121,18 +121,39 @@ if ! which git-lfs; then
   echo "git-lfs needs to be installed to use this script"
 fi
 
-# create a virtual environment and install pip dependencies
-if [[ ! -d ../venv ]] || [[ ! -e ../venv/bin/activate ]] && [[ ! -e ../venv/Scripts/activate ]]; then
-  echo  ""
-  echo "Setting up virtual environment"
-  mkdir -p ../venv
-  $python -m venv ../venv
+if ! command -v uv >/dev/null 2>&1; then
+  echo ""
+  echo "uv not found, installing..."
+
+  curl -LsSf https://astral.sh/uv/install.sh | sh
+
+  export PATH="$HOME/.local/bin:$PATH"
 fi
+
+sleep 50
+
+if [[ ! -d ../venv ]] || [[ ! -e ../venv/bin/activate && ! -e ../venv/Scripts/activate ]]; then
+  echo ""
+  echo "Setting up virtual environment"
+
+  mkdir -p ../venv
+
+  if command -v uv >/dev/null 2>&1; then
+    echo "Using uv to create Python 3.8 venv"
+    uv venv venv --python 3.8
+  else
+    echo "Falling back to python venv"
+    $python -m venv ../venv
+  fi
+fi
+
+# activate venv (cross-platform)
 if [[ -e ../venv/Scripts/activate ]]; then
   source ../venv/Scripts/activate
 else
   source ../venv/bin/activate
 fi
+
 $python -m pip install --upgrade pip
 $python -m pip install poetry
 echo -e "Finished checking dependencies\n"
