Fix bash script

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -40,7 +40,8 @@ read -p "Deploying amplipi project (development build) to $user_host, press any 
 
 # install dependencies as necessary
 inst=false
-if [[ $(which dpkg) ]]; then
+python='python'
+if which dpkg; then
   for dep in python3-venv python3-pip; do
     dpkg-query -s $dep 1>/dev/null 2>/dev/null || inst=true
   done
@@ -48,16 +49,17 @@ if [[ $(which dpkg) ]]; then
     sudo apt update
     sudo apt install python3-venv python3-pip
   fi
+  python='python3' # older version of ubuntu still use python3 to differentiate from python version 2
 else
-  which pip || echo "pip needs to be installed to use this script" && inst=true
-  if ! $inst; then
-    pip install venv || echo "Failed to install python virtual environments, you may need to install this manually" && inst=true
+  if ! which pip; then
+    echo "pip needs to be installed to use this script";
+    exit 1;
   fi
-  if $inst; then
+  if ! $python -m pip install venv; then
+    echo "Failed to install python virtual environments, you may need to install this manually"
     exit 1;
   fi
 fi
-
 # create a virtual environment and install pip dependencies
 if [[ ! -d ../venv ]]; then
   mkdir ../venv
