Make deploy script a little friendlier to AmpliPi devs

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -6,18 +6,21 @@ set -e
 # get directory that the script exists in
 cd "$( dirname "$0" )"
 
-# check if RPI_IP_ADDRESS is set
-if [[ -z "${RPI_IP_ADDRESS}" ]]; then
-  echo ""
-  echo "Please set RPI_IP_ADDRESS, for example:"
-  echo -e '\033[1;32mexport RPI_IP_ADDRESS=192.168.0.140\033[0m'
-  echo "for ssh key access"
-  echo -e '\033[1;32mexport RPI_IP_ADDRESS=pi@192.168.0.140\033[0m'
-  echo ""
-  exit 1
+if [[ $# -eq 1 ]] && [[ $1 == '--help' || $1 == '-h' ]] ; then
+    echo -e 'deploy USER@HOST\n  Install AmpliPi software on a remote system defined by USER@HOST (default: pi@amplipi.local)'
+    exit 0
+fi
+if [[ $# -eq 1 ]] ; then
+    user_host=$1
+elif [[ $# -eq 0 ]] ; then
+    user_host='pi@amplipi.local'
+else
+    echo -e "Error: Too many arguments specified.\nUsage:\n"
+    echo -e 'deploy USER@HOST\n  Install AmpliPi software on a remote system defined by USER@HOST (default: pi@amplipi.local)'
+    exit 1
 fi
 
-echo "Deploying amplipi project (development build) to $RPI_IP_ADDRESS"
+read -p "Deploying amplipi project (development build) to $user_host, press any key to continue (Ctrl-C to quit)" -n 1
 
 # TODO: deploy amplipi as a python installed package with pip or something similar
 # NOTE: this probably doesnt make sense until we use a more advanced version of poetry or figure out how to not spam the global directory with our scripts and other files?
@@ -33,12 +36,12 @@ sed -i 's/DISABLE_HW = False/DISABLE_HW = True/' ../amplipi/rt.py
 # copy stuff to board
 latest_release=$(ls -d -t ../dist/amplipi-*.tar.gz | head --lines=1)
 release_name=$(echo $latest_release | sed -e 's@../dist/@@' -e 's/.tar.gz//')
-echo "Copying $latest_release to $RPI_IP_ADDRESS"
-scp $latest_release $RPI_IP_ADDRESS:
+echo "Copying $latest_release to $user_host"
+scp $latest_release $user_host:
 echo "Making development folder on pi"
-ssh $RPI_IP_ADDRESS "mkdir -p amplipi-dev"
-echo "Extracting folder into $RPI_IP_ADDRESS:~/amplipi-dev"
-ssh $RPI_IP_ADDRESS "cd amplipi-dev && tar -xvf ../${release_name}.tar.gz && cp -a ${release_name}/* . && rm -r ${release_name}"
+ssh $user_host "mkdir -p amplipi-dev"
+echo "Extracting folder into $user_host:~/amplipi-dev"
+ssh $user_host "cd amplipi-dev && tar -xvf ../${release_name}.tar.gz && cp -a ${release_name}/* . && rm -r ${release_name}"
 echo "Configuring installation"
-ssh $RPI_IP_ADDRESS "chmod +x amplipi-dev/scripts/configure.py"
-ssh $RPI_IP_ADDRESS "./amplipi-dev/scripts/configure.py --os-deps --python-deps --web --restart-updater"
+ssh $user_host "chmod +x amplipi-dev/scripts/configure.py"
+ssh $user_host "./amplipi-dev/scripts/configure.py --os-deps --python-deps --web --restart-updater"
